### ISSUE TITLE
训练数据

### ISSUE THREAD

**Issue by Zhao6924** [chizhanyuefeng/Motion_recognition_tf#2]
您好，谢谢您的代码分享，请教一下，您在做视频动作识别的时候都是用哪些训练数据的，除了C3d神经网络模型，您还有什么可以推荐的?
 谢谢。

**Comment by chizhanyuefeng** [comment]
目前通用的有3种方法来做
– C3D :
Paper : https://arxiv.org/abs/1412.0767
博客讲解:
https://blog.csdn.net/u014380165/article/details/78
986416
– Two stream
Paper https://arxiv.org/abs/1604.06573
– Two stream +LSTM
Paper https://arxiv.org/abs/1503.08909

**Comment by chizhanyuefeng** [comment]
训练数据方面,我稍后会放出链接

**Comment by Zhao6924** [comment]
好的，十分感谢，我会继续关注您的的仓库学习您的代码。

**Comment by chizhanyuefeng** [comment]
@Zhao6924 训练和验证数据已更新在readme中
