### ISSUE TITLE
关于卷积核的shape

### ISSUE THREAD

**Issue by NieHw** [chizhanyuefeng/Motion_recognition_tf#3]
你好，我想依照你的网络结构复现实验。由于你还未提供 .model文件，我按照一般方法写了网络，由于输入是[batch, 16,112,112,3], 可是我不知道weight的shape如何来写？谢谢

**Comment by chizhanyuefeng** [comment]
周末我会更新readme，提供预训练模型

**Comment by 1916576591** [comment]
> 周末我会更新readme，提供预训练模型

你好，我运行test_c3d_network.py时，会调用c3d_network.py文件里的'class C3D_Network', 然后会提示缺少‘pretrain_model_path = './models/pretrain/sports1m_finetuning_ucf101.model'该文件？我该如何解决？谢谢

**Comment by 1916576591** [comment]
> 周末我会更新readme，提供预训练模型

你好，我用'test_c3d_network.py'文件测试时，该文件调用‘c3d_network.py’文件中的类C3D_Network，该类下有个路径：pretrain_model_path = './models/pretrain/model.ckpt’ ，我已换成了你所提供的预训练模型的路径，运行后提示“AssertionError: 找不着var_name/wc1参数”。然后我查看了一下你所提供的模型里面保存的参数，似乎只有全连接的weight&bias value（‘wd1’，‘wd2’，‘bd1’之类...）。请问我是哪里出错了吗？谢谢你的回答

**Comment by chizhanyuefeng** [comment]
@1916576591 是我疏忽,我忘记上传pretrain模型了.我这段代码,使用的是101的模型进行fintune,晚上我会把pretrain模型进行上传

**Comment by 1916576591** [comment]
> @1916576591 是我疏忽,我忘记上传pretrain模型了.我这段代码,使用的是101的模型进行fintune,晚上我会把pretrain模型进行上传

谢谢，我今天已经在开始训练了，由于我的显存不够，所以我将参数修改了一下batch_size=10, train_step=10000, depth=8，train = Train_C3D_Network(batch_size=10, pretrain=False)，最后的结果验验证集的正确率在0.65左右，测试集还没有开始验证。请问一下您最后的验证集和训练集的正确率是多少？我这样修改参数合适吗？

**Comment by chizhanyuefeng** [comment]
> > @1916576591 是我疏忽,我忘记上传pretrain模型了.我这段代码,使用的是101的模型进行fintune,晚上我会把pretrain模型进行上传
> 
> 谢谢，我今天已经在开始训练了，由于我的显存不够，所以我将参数修改了一下batch_size=10, train_step=10000, depth=8，train = Train_C3D_Network(batch_size=10, pretrain=False)，最后的结果验验证集的正确率在0.65左右，测试集还没有开始验证。请问一下您最后的验证集和训练集的正确率是多少？我这样修改参数合适吗？

你可以参考train_logs中我训练时候的生成日志

**Comment by 1916576591** [comment]
> > > @1916576591 是我疏忽,我忘记上传pretrain模型了.我这段代码,使用的是101的模型进行fintune,晚上我会把pretrain模型进行上传
> > 
> > 
> > 谢谢，我今天已经在开始训练了，由于我的显存不够，所以我将参数修改了一下batch_size=10, train_step=10000, depth=8，train = Train_C3D_Network(batch_size=10, pretrain=False)，最后的结果验验证集的正确率在0.65左右，测试集还没有开始验证。请问一下您最后的验证集和训练集的正确率是多少？我这样修改参数合适吗？
> 
> 你可以参考train_logs中我训练时候的生成日志

好哒~
