### ISSUE TITLE
关于预训练的模型

### ISSUE THREAD

**Issue by 1916576591** [chizhanyuefeng/Motion_recognition_tf#4]
您好，我想重复一下您这个项目，能上传一下.model文件吗，我是新手小白，没有这个文件跑不通了，拜托了

**Comment by chizhanyuefeng** [comment]
周末我会更新readme

**Comment by 1916576591** [comment]
大神更新了吗？我等得花儿都谢了~~>_<~~

**Comment by chizhanyuefeng** [comment]
@1916576591 已更新

**Comment by 1916576591** [comment]
@chizhanyuefeng 谢谢大神 ^_^ ！test_model已经收到了，可以直接测试了。然后我想自己训练的话，是不是需要pretrain文件？pretrain文件能不能也共享一下？也可以直接发我邮箱1916576591@qq.com
